apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collection-service
  template:
    metadata:
      labels:
        app: data-collection-service
    spec:
      containers:
      - name: data-collection-service
        image: girish445g/data_collection_service:latest
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: data-collection-service
spec:
  selector:
    app: data-collection-service
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: NodePort

