apiVersion: apps/v1
kind: Deployment
metadata:
  name: retraining-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retraining-service
  template:
    metadata:
      labels:
        app: retraining-service
    spec:
      containers:
      - name: retraining-service
        image: girish445g/retraining_service:latest
        ports:
        - containerPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: retraining-service
spec:
  selector:
    app: retraining-service
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8003
  type: NodePort

